## this is our first pandas tutorial


In [7]:
import pandas as pd
import numpy as np
df= pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


## create a data frame from a list

In [8]:
lst = ["geeks","for","geek"]
df=pd.DataFrame(lst,index=[2,3,4])
print(df)

       0
2  geeks
3    for
4   geek


## from numpy Array

In [16]:
# import numpy as np
# import pandas as pd
data = np.array([1,2,3,4])
print(data,data.shape)
print()
df= pd.DataFrame(data,index=[2,3,5,8],columns=['A'])
print(df)

[1 2 3 4] (4,)

   A
2  1
3  2
5  3
8  4


In [21]:
data = np.array([[1,2,3,4],[5,6,7,8]])
print(data,data.shape)
print()
df= pd.DataFrame(data)
print(df)

[[1 2 3 4]
 [5 6 7 8]] (2, 4)

   0  1  2  3
0  1  2  3  4
1  5  6  7  8


## DataFrame expects 1D or 2D-like data (rows and columns), not 3D.

In [23]:
data= np.array([[[1,2,3,4],
                 [3,4,5,5]],
                 [[7,8,9,0],
                  [9,8,7,6]]])
print(data,data.shape)

# df=pd.DataFrame(data)
# print(df)

[[[1 2 3 4]
  [3 4 5 5]]

 [[7 8 9 0]
  [9 8 7 6]]] (2, 2, 4)


### create dataframe using dictionary

#### DataFrame expects each value in the dictionary to be a list (or array) of the same length.

In [27]:
dct={
    "name":"dipok",
    "age": 21

}
print(dct)
# df=pd.DataFrame(dct)


{'name': 'dipok', 'age': 21}


In [29]:
df=pd.DataFrame([dct])
print(df)

    name  age
0  dipok   21


In [34]:
dct={
    "name": ["dipok","dipu","rifat","susmit","shimul","mamun"],
    "age" : [21,21,23,24,25,34]#all array must be the same length...
}

df=pd.DataFrame(dct)
print(df)

     name  age
0   dipok   21
1    dipu   21
2   rifat   23
3  susmit   24
4  shimul   25
5   mamun   34


### More practice


In [45]:
tp=(5,6,7)
lst=[
    
    {
        "name":"dipok",
        "age":21
    },{
        "dept":"cse",
        "building":"iict",
        "tuple":(1,2,3),
        tp:"tuple2"
    }

]

print(lst)
df=pd.DataFrame(lst)
print()
print(df)


[{'name': 'dipok', 'age': 21}, {'dept': 'cse', 'building': 'iict', 'tuple': (1, 2, 3), (5, 6, 7): 'tuple2'}]

    name   age dept building      tuple (5, 6, 7)
0  dipok  21.0  NaN      NaN        NaN       NaN
1    NaN   NaN  cse     iict  (1, 2, 3)    tuple2
