# This is for learning pandas Data Frame

## this code for create dataFrame from list data structure

In [3]:
import pandas as pd
import numpy as np
df=pd.DataFrame()

lst=np.array([12,22,33,44])
df=pd.DataFrame(lst)
print(df)

    0
0  12
1  22
2  33
3  44


#### this code for create dataFrame from dictionary data stucture
##### Each key in the dictionary represents a column name

In [9]:
tp=(1,2,3)
dct={
    "name":["dipok"],
    "dept": ["Cse"],
     "tp": [tp]
}

df=pd.DataFrame(dct)
print(df)

    name dept         tp
0  dipok  Cse  (1, 2, 3)


In [13]:
dct={
    "name":["dipok"] * len(tp),
    "dept": ["Cse"]* len(tp),
     "tp": tp
}
df=pd.DataFrame(dct)
print(df)

    name dept  tp
0  dipok  Cse   1
1  dipok  Cse   2
2  dipok  Cse   3


##### use 2d list to create data frame

In [15]:
lst=np.array([[12,4,4],
              [4,5,6],
              [67,7,675]])
print("list \n",lst)

df=pd.DataFrame(lst)
print("Data Frame\n",df)

list 
 [[ 12   4   4]
 [  4   5   6]
 [ 67   7 675]]
Data Frame
     0  1    2
0  12  4    4
1   4  5    6
2  67  7  675
