In [ ]:
import pandas as pd

df=pd.DataFrame()

print(df)
print(df.empty)


Empty DataFrame
Columns: []
Index: []
True


# From List

In [26]:
lst=[1,2,3,4]

df=pd.DataFrame(lst,index=[10,11,12,13])
df.columns=[999]
print(df)

lst=[[1,2.,3,4],
     [5,6,7],
     []]

print()
print(lst)
print()
df=pd.DataFrame(lst)
print(df)
# print(df[1])
d=df.loc[1,1]
print(d,type(d))

lst=[[[1,2,3],[30,4,5],[]],
     [[3,4,5],[6,7],[],[]]]
print(lst)
df=pd.DataFrame(lst)
print(df)

    999
10    1
11    2
12    3
13    4

[[1, 2.0, 3, 4], [5, 6, 7], []]

     0    1    2    3
0  1.0  2.0  3.0  4.0
1  5.0  6.0  7.0  NaN
2  NaN  NaN  NaN  NaN
6.0 <class 'numpy.float64'>
[[[1, 2, 3], [30, 4, 5], []], [[3, 4, 5], [6, 7], [], []]]
           0           1   2     3
0  [1, 2, 3]  [30, 4, 5]  []  None
1  [3, 4, 5]      [6, 7]  []    []


# from numpy array

In [39]:
import numpy as np

arr=np.array([[1,2,3],
              [4,5,6],
              [1,3,9]])
print(arr,end='\n\n')
df=pd.DataFrame(arr)
print(df)
print()

arr=np.array([[[1,2,3],[2,3,3]]])

print(arr)

# df=pd.DataFrame(arr)


[[1 2 3]
 [4 5 6]
 [1 3 9]]

   0  1  2
0  1  2  3
1  4  5  6
2  1  3  9

[[[1 2 3]
  [2 3 3]]]


In [49]:
dict1={
    'a':[1],
    'b':[2],
    'c':[3]
}
dict2={
    'a':5,
    'b':6,
    'c':7,
    'd':8
}

dict=[[dict1,dict2],
      [dict2]]


print(dict1,dict2)

df=pd.DataFrame(dict1)
print(df)

df=pd.DataFrame(dict)
print()
print(df)


{'a': [1], 'b': [2], 'c': [3]} {'a': 5, 'b': 6, 'c': 7, 'd': 8}
   a  b  c
0  1  2  3

                                  0                                 1
0    {'a': [1], 'b': [2], 'c': [3]}  {'a': 5, 'b': 6, 'c': 7, 'd': 8}
1  {'a': 5, 'b': 6, 'c': 7, 'd': 8}                              None


# From another dataFrame 

In [66]:
data={
    'a':[1,2,3,4],
    'b':[2,3,4,5]
}

df=pd.DataFrame(data)
print(df)
print(df['a'])
df2=pd.DataFrame(df[['a','b']])
print(df2)

series=pd.Series([1,2,3],index=[3,2,1],name='n')
print(series)
df=pd.DataFrame(series)
print(df)

   a  b
0  1  2
1  2  3
2  3  4
3  4  5
0    1
1    2
2    3
3    4
Name: a, dtype: int64
   a  b
0  1  2
1  2  3
2  3  4
3  4  5
3    1
2    2
1    3
Name: n, dtype: int64
   n
3  1
2  2
1  3


In [70]:
# Initialize data to Dicts of series.
d = {'one': pd.Series([10, 20, 30, 40],
                      index=['a', 'b', 'c', 'r'],name='dipu'),
     'two': pd.Series([10, 20, 30, 40],
                      index=['a', 'b', 'c', 'e'])}

# creates Dataframe.
df = pd.DataFrame(d)

print(df)

    one   two
a  10.0  10.0
b  20.0  20.0
c  30.0  30.0
e   NaN  40.0
r  40.0   NaN


## from from_dict


In [ ]:
data = {0: {'Name': 'Alice', 'Age': 25}, 1: {'Name': 'Bob', 'Age': 30, 'dept':'swe'}}
df = pd.DataFrame.from_dict(data, orient='columns')
print(df)


data = {0: {'Name': 'Alice', 'Age': 25}, 1: {'Name': 'Bob', 'Age': 30}}
df = pd.DataFrame.from_dict(data, orient='index')
print(df)

df=pd.DataFrame(data)
print(df)


          0    1
Name  Alice  Bob
Age      25   30
dept    NaN  swe
    Name  Age
0  Alice   25
1    Bob   30
          0    1
Name  Alice  Bob
Age      25   30


In [77]:
data = [
    {'Name': 'Alice', 'Info': {'Age': 25, 'City': 'NY'}},
    {'Name': 'Bob', 'Info': {'Age': 30, 'City': 'LA'}}
]

df = pd.json_normalize(data)
print(df)
print(pd.DataFrame(data))

    Name  Info.Age Info.City
0  Alice        25        NY
1    Bob        30        LA
    Name                       Info
0  Alice  {'Age': 25, 'City': 'NY'}
1    Bob  {'Age': 30, 'City': 'LA'}
