# with []Operator

In [28]:
# import module
import pandas as pd
import numpy as np

# assign data
df = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],
                          
                          
                          'Age': [30, 35, 37, 33, 34, 30],
                          
                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],
                          
                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})

print(df)

print(df[(df['Age']>30) & (df['Salary']>=90000)])

print()
print(df.loc[df['Age']>30,['Name',"Salary"]])

         Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
1    MONICA     35   93000         CHEF
2    PHOEBE     37   88000        MASUS
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT
5    JOEY       30   95000       ARTIST
         Name  Age  Salary          JOB
1    MONICA     35   93000         CHEF
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT

         Name  Salary
1    MONICA     93000
2    PHOEBE     88000
3    ROSS      120000
4    CHANDLER   94000


## numpy Where

In [29]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
brr=np.where(arr%2!=0)
print(arr,brr)

lst=[10,9,8,7,6,5,4,3,2,1]
# print(lst, np.where(lst%2==0))

series=pd.Series(lst)
print(series)

crr=np.where(series%2==0)
print(crr,type(crr))

[ 1  2  3  4  5  6  7  8  9 10] (array([0, 2, 4, 6, 8]),)
0    10
1     9
2     8
3     7
4     6
5     5
6     4
7     3
8     2
9     1
dtype: int64
(array([0, 2, 4, 6, 8]),) <class 'tuple'>


In [ ]:
print(df)
filteredValue=np.where((df['Age']>=30) & (df['Salary']>90000) & df['JOB'].str.startswith('C'))

print(filteredValue,type(filteredValue))
print(df.loc[filteredValue])



         Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
1    MONICA     35   93000         CHEF
2    PHOEBE     37   88000        MASUS
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT
5    JOEY       30   95000       ARTIST
(array([1]),) <class 'tuple'>
        Name  Age  Salary   JOB
1   MONICA     35   93000  CHEF


# Query

In [60]:
print(df.query("Age>30"))
print(df.loc[df['Age']>30])
d=df['Age']>30
print(d,type(d))

print('-------------------')
series=pd.Series([1,0,0,0])
# print(df.loc[series])

print("--------------")
df.index=['a','b','c','d','e','f']
# print(df.loc[series])////


         Name  Age  Salary          JOB
b    MONICA     35   93000         CHEF
c    PHOEBE     37   88000        MASUS
d    ROSS       33  120000  PALENTOLOGY
e    CHANDLER   34   94000           IT
         Name  Age  Salary          JOB
b    MONICA     35   93000         CHEF
c    PHOEBE     37   88000        MASUS
d    ROSS       33  120000  PALENTOLOGY
e    CHANDLER   34   94000           IT
a    False
b     True
c     True
d     True
e     True
f    False
Name: Age, dtype: bool <class 'pandas.core.series.Series'>
-------------------
--------------


In [54]:
print((df['Age']>30)& (df['Salary']>90000))
d=(df['Age']>30)& (df['Salary']>90000)
print(df[d])
print(df.loc[d])

0    False
1     True
2    False
3     True
4     True
5    False
dtype: bool
         Name  Age  Salary          JOB
1    MONICA     35   93000         CHEF
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT
         Name  Age  Salary          JOB
1    MONICA     35   93000         CHEF
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT


# eval

In [68]:
d=df.eval("Age>30 & Salary>=90000 & JOB.str.startswith('I')")
print(d)
print(df[d])

a    False
b    False
c    False
d    False
e     True
f    False
dtype: bool
       Name  Age  Salary JOB
e  CHANDLER   34   94000  IT
